ourproxy:
  image: registry.local:5050/ourproxy:latest
  ports:
    - "80:80"
  links:
    - ourjsonserver

ourjsonserver:
    image: registry.local:5050/ourjsonserver:latest
    ports:
        - "3000:3000"

serverskelton:
    image: registry.local:5050/serverskelton:latest
    ports:
        - "8081:8081"
    volumes:
        - /Users/toukubo/mocking_proxy/serverskelton:/opt/app
