FROM cloud_os_front_nginx_4

EXPOSE 443
EXPOSE 80

COPY proxy.conf /etc/nginx/conf.d/proxy.conf

#CMD ["service nginx start"]
CMD ["/bin/sh","-c","/etc/init.d/nginx start && /bin/bash"]
# CMD ["/bin/sh","-c","/etc/init.d/nginx start"]
# CMD ["service nginx start && /bin/bash"]
# CMD ["/sbin/service nginx start"]
