FROM our_proxy:latest

# based on this : https://github.com/dockerfile/nginx

COPY proxy.conf /etc/nginx/sites-enabled/proxy.conf

# Define mountable directories.
# VOLUME ["/etc/nginx/sites-enabled", "/etc/nginx/certs", "/etc/nginx/conf.d", "/var/log/nginx", "/var/www/html"]

# Define working directory.
WORKDIR /etc/nginx

# Define default command.
CMD ["nginx"]

# Expose ports.
EXPOSE 80
EXPOSE 443
